// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2-devel
// 	protoc        (unknown)
// source: model/user/common.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Типы сортировки
type TypeDirection int32

const (
	// от меньшего к большему
	TypeDirection_TYPE_ASC TypeDirection = 0
	// от большего к меньшему
	TypeDirection_TYPE_DESC TypeDirection = 1
)

// Enum value maps for TypeDirection.
var (
	TypeDirection_name = map[int32]string{
		0: "TYPE_ASC",
		1: "TYPE_DESC",
	}
	TypeDirection_value = map[string]int32{
		"TYPE_ASC":  0,
		"TYPE_DESC": 1,
	}
)

func (x TypeDirection) Enum() *TypeDirection {
	p := new(TypeDirection)
	*p = x
	return p
}

func (x TypeDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_model_user_common_proto_enumTypes[0].Descriptor()
}

func (TypeDirection) Type() protoreflect.EnumType {
	return &file_model_user_common_proto_enumTypes[0]
}

func (x TypeDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeDirection.Descriptor instead.
func (TypeDirection) EnumDescriptor() ([]byte, []int) {
	return file_model_user_common_proto_rawDescGZIP(), []int{0}
}

// Состояние списка
type ListCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Взять элементов
	Take uint32 `protobuf:"varint,1,opt,name=take,proto3" json:"take,omitempty"`
	// Пропустить элементов
	Skip uint32 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	// Сортировать элементы по ключу
	DirectionKey string `protobuf:"bytes,3,opt,name=direction_key,json=directionKey,proto3" json:"direction_key,omitempty"`
	// Направление сортировки (ASC OR DESC)
	Direction TypeDirection `protobuf:"varint,4,opt,name=direction,proto3,enum=user.common.TypeDirection" json:"direction,omitempty"`
	// Limit && Offset
	Limit  int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListCondition) Reset() {
	*x = ListCondition{}
	mi := &file_model_user_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCondition) ProtoMessage() {}

func (x *ListCondition) ProtoReflect() protoreflect.Message {
	mi := &file_model_user_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCondition.ProtoReflect.Descriptor instead.
func (*ListCondition) Descriptor() ([]byte, []int) {
	return file_model_user_common_proto_rawDescGZIP(), []int{0}
}

func (x *ListCondition) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *ListCondition) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListCondition) GetDirectionKey() string {
	if x != nil {
		return x.DirectionKey
	}
	return ""
}

func (x *ListCondition) GetDirection() TypeDirection {
	if x != nil {
		return x.Direction
	}
	return TypeDirection_TYPE_ASC
}

func (x *ListCondition) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCondition) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Состояние Временного интервала (даты включительно)
// EXAMPLE: 20.01.2025 - 20.02.2025 (включительно)
type TimeRangeCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Начиная с даты
	From *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Заканчивая датой
	To *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *TimeRangeCondition) Reset() {
	*x = TimeRangeCondition{}
	mi := &file_model_user_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRangeCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRangeCondition) ProtoMessage() {}

func (x *TimeRangeCondition) ProtoReflect() protoreflect.Message {
	mi := &file_model_user_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRangeCondition.ProtoReflect.Descriptor instead.
func (*TimeRangeCondition) Descriptor() ([]byte, []int) {
	return file_model_user_common_proto_rawDescGZIP(), []int{1}
}

func (x *TimeRangeCondition) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TimeRangeCondition) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

// Состояние интервала между значениями
type RangeCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Начиная с значения
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Заканчивая значением (включительно)
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *RangeCondition) Reset() {
	*x = RangeCondition{}
	mi := &file_model_user_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeCondition) ProtoMessage() {}

func (x *RangeCondition) ProtoReflect() protoreflect.Message {
	mi := &file_model_user_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeCondition.ProtoReflect.Descriptor instead.
func (*RangeCondition) Descriptor() ([]byte, []int) {
	return file_model_user_common_proto_rawDescGZIP(), []int{2}
}

func (x *RangeCondition) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RangeCondition) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

var File_model_user_common_proto protoreflect.FileDescriptor

var file_model_user_common_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x01, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x6b,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6b, 0x69,
	0x70, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x70,
	0x0a, 0x12, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x6f,
	0x22, 0x34, 0x0a, 0x0e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x2a, 0x2c, 0x0a, 0x0d, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x41, 0x53, 0x43, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45,
	0x53, 0x43, 0x10, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x49, 0x49, 0x49, 0x42, 0x79, 0x74, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_user_common_proto_rawDescOnce sync.Once
	file_model_user_common_proto_rawDescData = file_model_user_common_proto_rawDesc
)

func file_model_user_common_proto_rawDescGZIP() []byte {
	file_model_user_common_proto_rawDescOnce.Do(func() {
		file_model_user_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_user_common_proto_rawDescData)
	})
	return file_model_user_common_proto_rawDescData
}

var file_model_user_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_user_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_model_user_common_proto_goTypes = []any{
	(TypeDirection)(0),            // 0: user.common.TypeDirection
	(*ListCondition)(nil),         // 1: user.common.ListCondition
	(*TimeRangeCondition)(nil),    // 2: user.common.TimeRangeCondition
	(*RangeCondition)(nil),        // 3: user.common.RangeCondition
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_model_user_common_proto_depIdxs = []int32{
	0, // 0: user.common.ListCondition.direction:type_name -> user.common.TypeDirection
	4, // 1: user.common.TimeRangeCondition.from:type_name -> google.protobuf.Timestamp
	4, // 2: user.common.TimeRangeCondition.to:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_user_common_proto_init() }
func file_model_user_common_proto_init() {
	if File_model_user_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_user_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_user_common_proto_goTypes,
		DependencyIndexes: file_model_user_common_proto_depIdxs,
		EnumInfos:         file_model_user_common_proto_enumTypes,
		MessageInfos:      file_model_user_common_proto_msgTypes,
	}.Build()
	File_model_user_common_proto = out.File
	file_model_user_common_proto_rawDesc = nil
	file_model_user_common_proto_goTypes = nil
	file_model_user_common_proto_depIdxs = nil
}
